# Use a smaller base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Install dependencies for OpenCV etc.
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY req_app_env1.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY model.h5 .
RUN mkdir temp

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
